# Site settings
title: Inf-2201 Operating System Fundamentals (Spring 2017)
# email: larsab@cs.uit.no
description: > # this means to ignore newlines until "baseurl:"
  Inf-2201 Operating System Fundamentals, spring 2017, University of Troms√∏. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uit-inf-2201-s17.github.io/" 

# Build settings
markdown: kramdown
